#/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created: Mon Jul  7 12:44:04 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(593, 677)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(450, 400))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("")
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setSizeGripEnabled(False)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setContentsMargins(50, 20, 50, 20)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nine = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout_3.addWidget(self.nine, 2, 2, 1, 1)
        self.four = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout_3.addWidget(self.four, 3, 0, 1, 1)
        self.seven = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout_3.addWidget(self.seven, 2, 0, 1, 1)
        self.five = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout_3.addWidget(self.five, 3, 1, 1, 1)
        self.six = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout_3.addWidget(self.six, 3, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout_3.addWidget(self.eight, 2, 1, 1, 1)
        self.one = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.one.setFont(font)
        self.one.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Spain))
        self.one.setAutoRepeatDelay(301)
        self.one.setObjectName("one")
        self.gridLayout_3.addWidget(self.one, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 5)
        self.three = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout_3.addWidget(self.three, 4, 2, 1, 1)
        self.butCE = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.butCE.setFont(font)
        self.butCE.setObjectName("butCE")
        self.gridLayout_3.addWidget(self.butCE, 7, 4, 1, 1)
        self.Exe = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.Exe.setFont(font)
        self.Exe.setObjectName("Exe")
        self.gridLayout_3.addWidget(self.Exe, 4, 4, 1, 1)
        self.plus_minus = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.plus_minus.setFont(font)
        self.plus_minus.setObjectName("plus_minus")
        self.gridLayout_3.addWidget(self.plus_minus, 7, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout_3.addWidget(self.zero, 7, 0, 1, 1)
        self.two = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout_3.addWidget(self.two, 4, 1, 1, 1)
        self.decimal = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.decimal.setFont(font)
        self.decimal.setAutoFillBackground(False)
        self.decimal.setObjectName("decimal")
        self.gridLayout_3.addWidget(self.decimal, 7, 1, 1, 1)
        self.subtract = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.subtract.setFont(font)
        self.subtract.setObjectName("subtract")
        self.gridLayout_3.addWidget(self.subtract, 2, 4, 1, 1)
        self.product = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.product.setFont(font)
        self.product.setObjectName("product")
        self.gridLayout_3.addWidget(self.product, 3, 3, 1, 1)
        self.sum = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.sum.setFont(font)
        self.sum.setObjectName("sum")
        self.gridLayout_3.addWidget(self.sum, 2, 3, 1, 1)
        self.div = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.div.setFont(font)
        self.div.setObjectName("div")
        self.gridLayout_3.addWidget(self.div, 3, 4, 1, 1)
        self.Del = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.Del.setFont(font)
        self.Del.setObjectName("Del")
        self.gridLayout_3.addWidget(self.Del, 4, 3, 1, 1)
        self.butC = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.butC.setFont(font)
        self.butC.setObjectName("butC")
        self.gridLayout_3.addWidget(self.butC, 7, 3, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.gridLayout_3)
        spacerItem = QtWidgets.QSpacerItem(18, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.factorial = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.factorial.setFont(font)
        self.factorial.setObjectName("factorial")
        self.gridLayout_2.addWidget(self.factorial, 0, 0, 1, 1)
        self.nroot = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.nroot.setFont(font)
        self.nroot.setObjectName("nroot")
        self.gridLayout_2.addWidget(self.nroot, 0, 1, 1, 1)
        self.cubicroot = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.cubicroot.setFont(font)
        self.cubicroot.setObjectName("cubicroot")
        self.gridLayout_2.addWidget(self.cubicroot, 0, 2, 1, 1)
        self.sqrt = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.sqrt.setFont(font)
        self.sqrt.setObjectName("sqrt")
        self.gridLayout_2.addWidget(self.sqrt, 0, 3, 1, 1)
        self.inverse = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.inverse.setFont(font)
        self.inverse.setObjectName("inverse")
        self.gridLayout_2.addWidget(self.inverse, 0, 4, 1, 1)
        self.pow = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.pow.setFont(font)
        self.pow.setObjectName("pow")
        self.gridLayout_2.addWidget(self.pow, 1, 0, 1, 1)
        self.powerof10 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.powerof10.setFont(font)
        self.powerof10.setObjectName("powerof10")
        self.gridLayout_2.addWidget(self.powerof10, 1, 1, 1, 1)
        self.log = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 1, 2, 1, 1)
        self.powerofe = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.powerofe.setFont(font)
        self.powerofe.setObjectName("powerofe")
        self.gridLayout_2.addWidget(self.powerofe, 1, 3, 1, 1)
        self.logn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.logn.setFont(font)
        self.logn.setObjectName("logn")
        self.gridLayout_2.addWidget(self.logn, 1, 4, 1, 1)
        self.mod = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.mod.setFont(font)
        self.mod.setObjectName("mod")
        self.gridLayout_2.addWidget(self.mod, 2, 0, 1, 1)
        self.combinatorial = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.combinatorial.setFont(font)
        self.combinatorial.setObjectName("combinatorial")
        self.gridLayout_2.addWidget(self.combinatorial, 2, 1, 1, 1)
        self.permutation = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.permutation.setFont(font)
        self.permutation.setObjectName("permutation")
        self.gridLayout_2.addWidget(self.permutation, 2, 2, 1, 1)
        self.Degrees = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.Degrees.setFont(font)
        self.Degrees.setObjectName("Degrees")
        self.gridLayout_2.addWidget(self.Degrees, 2, 4, 1, 1)
        self.percentage = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.percentage.setFont(font)
        self.percentage.setObjectName("percentage")
        self.gridLayout_2.addWidget(self.percentage, 2, 3, 1, 1)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 64, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(572, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sin = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.sin.setFont(font)
        self.sin.setObjectName("sin")
        self.gridLayout.addWidget(self.sin, 0, 0, 1, 1)
        self.asin = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.asin.setFont(font)
        self.asin.setObjectName("asin")
        self.gridLayout.addWidget(self.asin, 1, 0, 1, 1)
        self.atan = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.atan.setFont(font)
        self.atan.setObjectName("atan")
        self.gridLayout.addWidget(self.atan, 1, 2, 1, 1)
        self.sec = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.sec.setFont(font)
        self.sec.setObjectName("sec")
        self.gridLayout.addWidget(self.sec, 2, 0, 1, 1)
        self.cos = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.cos.setFont(font)
        self.cos.setObjectName("cos")
        self.gridLayout.addWidget(self.cos, 0, 1, 1, 1)
        self.tan = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.tan.setFont(font)
        self.tan.setObjectName("tan")
        self.gridLayout.addWidget(self.tan, 0, 2, 1, 1)
        self.acos = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.acos.setFont(font)
        self.acos.setObjectName("acos")
        self.gridLayout.addWidget(self.acos, 1, 1, 1, 1)
        self.tanh = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.tanh.setFont(font)
        self.tanh.setObjectName("tanh")
        self.gridLayout.addWidget(self.tanh, 3, 2, 1, 1)
        self.enumber = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.enumber.setFont(font)
        self.enumber.setObjectName("enumber")
        self.gridLayout.addWidget(self.enumber, 4, 1, 1, 1)
        self.cosec = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.cosec.setFont(font)
        self.cosec.setObjectName("cosec")
        self.gridLayout.addWidget(self.cosec, 2, 1, 1, 1)
        self.cotg = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.cotg.setFont(font)
        self.cotg.setObjectName("cotg")
        self.gridLayout.addWidget(self.cotg, 2, 2, 1, 1)
        self.pi = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.pi.setFont(font)
        self.pi.setObjectName("pi")
        self.gridLayout.addWidget(self.pi, 4, 0, 1, 1)
        self.sinh = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.sinh.setFont(font)
        self.sinh.setObjectName("sinh")
        self.gridLayout.addWidget(self.sinh, 3, 0, 1, 1)
        self.goldnumber = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.goldnumber.setFont(font)
        self.goldnumber.setObjectName("goldnumber")
        self.gridLayout.addWidget(self.goldnumber, 4, 2, 1, 1)
        self.cosh = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.cosh.setFont(font)
        self.cosh.setObjectName("cosh")
        self.gridLayout.addWidget(self.cosh, 3, 1, 1, 1)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(515, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(14, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.About = QtWidgets.QPushButton(Dialog)
        self.About.setIcon(icon)
        self.About.setIconSize(QtCore.QSize(32, 32))
        self.About.setCheckable(False)
        self.About.setFlat(False)
        self.About.setObjectName("About")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.About)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SuperPyQtCalculator"))
        self.nine.setText(_translate("Dialog", "9"))
        self.four.setText(_translate("Dialog", "4"))
        self.seven.setText(_translate("Dialog", "7"))
        self.five.setText(_translate("Dialog", "5"))
        self.six.setText(_translate("Dialog", "6"))
        self.eight.setText(_translate("Dialog", "8"))
        self.one.setText(_translate("Dialog", "1"))
        self.three.setText(_translate("Dialog", "3"))
        self.butCE.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Clear the screen</p></body></html>"))
        self.butCE.setText(_translate("Dialog", "CE"))
        self.Exe.setText(_translate("Dialog", "="))
        self.plus_minus.setText(_translate("Dialog", "\u00b1"))
        self.zero.setText(_translate("Dialog", "0"))
        self.two.setText(_translate("Dialog", "2"))
        self.decimal.setText(_translate("Dialog", "\u00b7"))
        self.subtract.setText(_translate("Dialog", "−"))
        self.product.setText(_translate("Dialog", "\u00d7"))
        self.sum.setText(_translate("Dialog", "+"))
        self.div.setText(_translate("Dialog", "\u00f7"))
        self.Del.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Delete a digit</p></body></html>"))
        self.Del.setText(_translate("Dialog", "DEL"))
        self.butC.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Clear all</p></body></html>"))
        self.butC.setText(_translate("Dialog", "C"))
        self.factorial.setText(_translate("Dialog", "n!"))
        self.nroot.setText(_translate("Dialog", "\u207f\u221a"))
        self.cubicroot.setText(_translate("Dialog", "\u00b3\u221a"))
        self.sqrt.setText(_translate("Dialog", "\u221a"))
        self.inverse.setText(_translate("Dialog", "x\u2013\u00b9"))
        self.pow.setText(_translate("Dialog", "x\u207f"))
        self.powerof10.setText(_translate("Dialog", "10\u207f"))
        self.log.setText(_translate("Dialog", "Log"))
        self.powerofe.setText(_translate("Dialog", "\u212e\u207f"))
        self.logn.setText(_translate("Dialog", "Ln"))
        self.mod.setText(_translate("Dialog", "Mod"))
        self.combinatorial.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Combinatorial of <span style=\" font-weight:600;\">n</span> elements with <span style=\" font-weight:600;\">r</span> repetitions</p></body></html>"))
        self.combinatorial.setText(_translate("Dialog", "nCr"))
        self.permutation.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Variations of <span style=\" font-weight:600;\">n</span> elements with <span style=\" font-weight:600;\">r</span> repetitions</p></body></html>"))
        self.permutation.setText(_translate("Dialog", "nPr"))
        self.Degrees.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">Converts a number to sexagesimal degrees</p></body></html>"))
        self.Degrees.setText(_translate("Dialog", "\u00b0  \u02bc  \u02ee"))
        self.percentage.setText(_translate("Dialog", "%"))
        self.sin.setText(_translate("Dialog", "sin"))
        self.asin.setText(_translate("Dialog", "asin"))
        self.atan.setText(_translate("Dialog", "atan"))
        self.sec.setText(_translate("Dialog", "sec"))
        self.cos.setText(_translate("Dialog", "cos"))
        self.tan.setText(_translate("Dialog", "tan"))
        self.acos.setText(_translate("Dialog", "acos"))
        self.tanh.setText(_translate("Dialog", "tanh"))
        self.enumber.setText(_translate("Dialog", "\u212e"))
        self.cosec.setText(_translate("Dialog", "cosec"))
        self.cotg.setText(_translate("Dialog", "cotg"))
        self.pi.setText(_translate("Dialog", "\u03c0"))
        self.sinh.setText(_translate("Dialog", "sinh"))
        self.goldnumber.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">The golden number</p></body></html>"))
        self.goldnumber.setText(_translate("Dialog", "\u03c6"))
        self.cosh.setText(_translate("Dialog", "cosh"))
        self.About.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">About the program</p></body></html>"))
        self.About.setText(_translate("Dialog", " About"))

import img_rc
